routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});
Auth::routes();
//Route::post('/active', 'Admin\AdminSettingController@active')->middleware('web');
Route::post('saveAdminData', 'Admin\AdminSettingController@setup');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth','coder']], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});
Route::group(['middleware' => ['auth', 'coder']], function () {

	Route::group(['namespace' => 'Admin'], function () {

		Route::resources([
			'roles' => 'RolesController',
			'users' => 'UsersController',
			'categories' => 'CategoryController',
			'subcategories' => 'SubCategoryController',
			'branch' => 'BranchController',
			'offers' => 'OfferController',
			'notification' => 'StaticNotiController',
			'employee' => 'EmployeeInfoController',
		]);
		Route::get('review', 'ReviewController@index')->name('review.index');
		Route::get('review/{id}', 'ReviewController@delete')->name('review.delete');
		Route::get('pp', 'AdminSettingController@pp')->name('pp');
		Route::post('pp/update', 'AdminSettingController@updatePP')->name('pp.update');
		// module
		Route::post('twilio/update', 'TwilioController@updateTwilio')->name('twilio.update');
		Route::post('onesignal', 'StaticNotiController@updateOnesignl')->name('onesignal.update');
		Route::post('base', 'AdminSettingController@updateBase')->name('base.update');
		Route::post('stripe', 'StripeController@updateStripe')->name('stripe.update');
		Route::post('paypal', 'PaypalController@updatePaypal')->name('paypal.update');
		Route::post('razor', 'RazorController@updatePaypal')->name('razor.update');
		// module
		Route::get('report', 'BranchController@reportIndex')->name('report.index');
		Route::post('report', 'BranchController@createReport')->name('report.create');
		Route::get('custom/notification', 'StaticNotiController@customIndex')->name('custom.index');
		Route::post('custom/notification/user', 'StaticNotiController@customUser')->name('custom.user');

		Route::get('setting', 'AdminSettingController@index')->name('setting.index');
		Route::post('setting/basic', 'AdminSettingController@basicUpdate')->name('setting.basic');

		Route::post('user/notification', 'UsersController@notifications');

	});
});

Route::get('appuser', 'AppUsersController@index')->name('appuser.index');
Route::post('appuser/status/{id}', 'AppUsersController@changeStatus')->name('appuser.statusChange');

Route::get('booking', 'BookingMasterController@index')->name('booking.index');
Route::get('booking/{id}', 'BookingMasterController@show')->name('booking.show');
Route::get('booking/{id}/{status}', 'BookingMasterController@statusChange')->name('booking.status');
Route::get('payment/{id}', 'BookingMasterController@collectPayment')->name('booking.paymentstatus');

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-dark scrollbar-light" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main"
            aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
            <img src="{{ asset('argon') }}/img/brand/logo-barber.png" class="navbar-brand-img" alt="...">
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                            <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('My profile') }}</span>
                    </a>

                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/logo-barber.png">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse"
                            data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false"
                            aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            {{-- <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended"
                        placeholder="{{ __('Search') }}" aria-label="Search">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <span class="fa fa-search"></span>
                </div>
            </div>
        </div>
        </form> --}}
        <!-- Navigation -->
        <ul class="navbar-nav">
            <h6 class="navbar-heading text-muted text-white">Navegação</h6>
            @can('dashboard')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ route('home') }}">
                    <i class="fas fa-tachometer-alt text-primary"></i> {{ __('Painel') }}
                </a>
            </li>
            @endcan

            @can('role_access')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{route('roles.index')}}">
                    <i class="far fa-id-badge text-blue"></i> {{ __('Permissões') }}
                </a>
            </li>
            @endcan
            @can('user_access')

            <li class="nav-item">
                <a class="nav-link text-white" href="{{route('users.index')}}">
                    <i class="far fa-user text-blue"></i> {{ __('Usuários') }}
                </a>
            </li>
            @endcan
            @can('category_access')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{route('categories.index')}}">
                    <i class="far fa-folder text-blue"></i> {{ __('Categorias') }}
                </a>
            </li>
            @endcan
            @can('subcategory_access')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{route('subcategories.index')}}">
                    <i class="far fa-list-alt text-blue"></i> {{ __('Sub Categorias') }}
                </a>
            </li>
            @endcan
            @canany(['employee_access','branch_employee_access'])
            <li class="nav-item">
                <a class="nav-link text-white" href="{{route('employee.index')}}">
                    <i class="fas fa-user-tie text-blue"></i> {{ __('Funcionários') }}
                </a>
            </li>
            @endcan

            @canany(['branch_access','branch_manager_access'])
            <li class="nav-item">
                <a class="nav-link text-white" href="{{route('branch.index')}}">
                    <i class="fas fa-store-alt text-blue"></i> {{ __('Filiais') }}
                </a>
            </li>
            @endcan
            @can('offer_access')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{route('offers.index')}}">
                    <i class="fas fa-gift text-blue"></i> {{ __('Ofertas') }}
                </a>
            </li>
            @endcan
            @can('appuser_access')
            <li class="nav-item">
                {{-- appuser.index --}}
                <a class="nav-link text-white" href="{{route('appuser.index')}}">
                    <i class="fas fa-shower text-blue"></i> {{ __('Clientes') }}
                </a>
            </li>
            @endcan
            @canany(['booking_access','branch_booking_access'])
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ route('booking.index') }}">
                    <i class="fas fa-cut text-blue"></i> {{ __('Agendamentos') }}
                </a>
            </li>
            @endcan
            @can('notification_access')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ route('notification.index') }}">
                    <i class="far fa-bell text-blue"></i> {{ __('Notificação') }}
                </a>
            </li>
            @endcan
            @can('report_access')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ route('report.index') }}">
                    <i class="far fa-file-word text-blue"></i> {{ __('Report') }}
                </a>
            </li>
            @endcan
            @can('custom_notification_access')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ route('custom.index') }}">
                    <i class="fab fa-viber text-blue"></i> {{ __('Custom Notification') }}
                </a>
            </li>
            @endcan
            @can('setting_access')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ route('setting.index') }}">
                    <i class="far fa-clock text-blue"></i> {{ __('Setting') }}
                </a>
            </li>
            @endcan
            @can('privacy_access')
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ route('pp') }}">
                    <i class="far fa-handshake text-blue"></i> {{ __('Privacy and Policy') }}
                </a>
            </li>
            @endcan
            @canany(['review_access','branch_review_access'])
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ route('review.index') }}">
                    <i class="far fa-smile-beam text-blue"></i> {{ __('Review') }}
                </a>
            </li>
            @endcan
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ route('logout') }}">
                    <i class="ni ni-user-run text-blue"></i> {{ __('Sign out') }}
                </a>
            </li>

        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        {{-- <h6 class="navbar-heading text-muted">Documentation</h6> --}}
        <!-- Navigation -->
        {{-- <ul class="navbar-nav mb-md-3">
                <li class="nav-item">
                    <a class="nav-link"
                        href="https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html">
                        <i class="ni ni-spaceship"></i> Getting started
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        href="https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html">
                        <i class="ni ni-palette"></i> Foundation
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        href="https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html">
                        <i class="ni ni-ui-04"></i> Components
                    </a>
                </li>
            </ul> --}}
    </div>
    </div>
</nav>